{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "d9d0b0d3-5a4b-4274-b0f3-a49417aa9604",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[CONFIG]\n",
      "MOTHER_U: <FULL_PRF_ROOT>\\abcpipeline_full\\mother_U_v1.jsonl\n",
      "OUT_DIR: <FULL_PRF_ROOT>\\YL\\HXYZ\n",
      "LLM_30B_URL: http://127.0.0.1:8081/v1/chat/completions\n",
      "N_AUTO: 2000 N_DISPUTE: 2000 INCLUDE_STRONGC_ALL: True\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# PRF Core Experiment (HXYZ)\n",
    "# Direct 30B baseline on stratified sample from mother_U_v1.jsonl\n",
    "# - Resume supported\n",
    "# - Progress bars\n",
    "# - Fail-log (controlled landing)\n",
    "# - NEVER modifies mother_U\n",
    "# Outputs -> <FULL_PRF_ROOT>\\YL\\HXYZ\n",
    "# ============================================================\n",
    "\n",
    "import os, re, io, json, time, base64, random, hashlib\n",
    "from pathlib import Path\n",
    "from typing import Dict, Any, List, Optional, Tuple\n",
    "\n",
    "import requests\n",
    "import numpy as np\n",
    "from PIL import Image\n",
    "from tqdm import tqdm\n",
    "\n",
    "# -------------------------\n",
    "# Paths\n",
    "# -------------------------\n",
    "ROOT = Path(r\"<FULL_PRF_ROOT>\")\n",
    "PIPE_DIR = ROOT / \"abcpipeline_full\"\n",
    "\n",
    "MOTHER_U = PIPE_DIR / \"mother_U_v1.jsonl\"  # READ ONLY\n",
    "assert MOTHER_U.exists(), f\"Missing mother_U: {MOTHER_U}\"\n",
    "\n",
    "OUT_DIR = ROOT / \"YL\" / \"HXYZ\"\n",
    "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# (Ablation output dir reserved; not used in core experiment)\n",
    "ABL_DIR = ROOT / \"YL\" / \"XRYZ\"\n",
    "ABL_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# -------------------------\n",
    "# Direct 30B endpoint\n",
    "# -------------------------\n",
    "LLM_30B_URL = \"http://127.0.0.1:8081/v1/chat/completions\"\n",
    "MODEL_30B = \"qwen3-vl-30b\"  # if your server ignores this, it's still OK.\n",
    "\n",
    "# -------------------------\n",
    "# Sampling plan (stratified)\n",
    "# -------------------------\n",
    "SEED = 20260206\n",
    "N_AUTO = 2000\n",
    "N_DISPUTE = 2000\n",
    "INCLUDE_STRONGC_ALL = True   # include all strong-C gate pairs if present\n",
    "DELTA_STRONG = -0.2          # for identifying strong-C by delta\n",
    "\n",
    "# -------------------------\n",
    "# Image compact (same style as your pipeline)\n",
    "# -------------------------\n",
    "COMPACT_LONG_SIDE = 768\n",
    "COMPACT_JPEG_Q = 75\n",
    "\n",
    "# -------------------------\n",
    "# Runtime knobs\n",
    "# -------------------------\n",
    "RESUME = True\n",
    "TIMEOUT_30B = 600\n",
    "RETRY_30B = 1\n",
    "TEMP_30B = 0.0\n",
    "\n",
    "# -------------------------\n",
    "# Output files (core experiment)\n",
    "# -------------------------\n",
    "SAMPLE_JSONL = OUT_DIR / \"sample_pairs_stratified_v1.jsonl\"\n",
    "PRED_JSONL   = OUT_DIR / \"direct30b_pred_v1.jsonl\"\n",
    "DONE_TXT     = OUT_DIR / \"direct30b_done_pairs.txt\"\n",
    "FAIL_JSONL   = OUT_DIR / \"direct30b_failed_v1.jsonl\"\n",
    "\n",
    "METRICS_JSON = OUT_DIR / \"core_metrics_v1.json\"\n",
    "METRICS_CSV  = OUT_DIR / \"core_metrics_v1.csv\"\n",
    "DISAGREE_JSONL = OUT_DIR / \"disagreements_sample_v1.jsonl\"\n",
    "\n",
    "print(\"[CONFIG]\")\n",
    "print(\"MOTHER_<LOCAL_DRIVE_U>\", MOTHER_U)\n",
    "print(\"OUT_DIR:\", OUT_DIR)\n",
    "print(\"LLM_30B_URL:\", LLM_30B_URL)\n",
    "print(\"N_AUTO:\", N_AUTO, \"N_DISPUTE:\", N_DISPUTE, \"INCLUDE_STRONGC_ALL:\", INCLUDE_STRONGC_ALL)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "0b6412cf-8369-4ec7-94e9-605b3b8b19ee",
   "metadata": {},
   "outputs": [],
   "source": [
    "def now_iso():\n",
    "    return time.strftime(\"%Y-%m-%dT%H:%M:%S\", time.localtime())\n",
    "\n",
    "def key_of(qid: int, cid: int) -> str:\n",
    "    return f\"{int(qid)}_{int(cid)}\"\n",
    "\n",
    "def read_done_set(done_path: Path) -> set:\n",
    "    if not (RESUME and done_path.exists()):\n",
    "        return set()\n",
    "    s = set()\n",
    "    with done_path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            t = line.strip()\n",
    "            if <LOCAL_DRIVE_T>\n",
    "                s.add(t)\n",
    "    return s\n",
    "\n",
    "def append_done(done_path: Path, k: str):\n",
    "    with done_path.open(\"a\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        f.write(k + \"\\n\")\n",
    "\n",
    "def append_fail(fail_path: Path, obj: dict):\n",
    "    with fail_path.open(\"a\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        f.write(json.dumps(obj, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "def extract_json(text: str) -> dict:\n",
    "    t = text.strip()\n",
    "    if t.startswith(\"{\") and t.endswith(\"}\"):\n",
    "        return json.loads(t)\n",
    "    m = re.search(r\"\\{[\\s\\S]*\\}\", t)\n",
    "    if not <LOCAL_DRIVE_M>\n",
    "        raise ValueError(\"No JSON object found in model output\")\n",
    "    return json.loads(m.group(0))\n",
    "\n",
    "def img_to_data_url(path: str) -> str:\n",
    "    img = Image.open(path).convert(\"RGB\")\n",
    "    w, h = img.size\n",
    "    m = max(w, h)\n",
    "    if m > COMPACT_LONG_SIDE:\n",
    "        s = COMPACT_LONG_SIDE / m\n",
    "        img = img.resize((max(1, int(w*s)), max(1, int(h*s))), Image.BICUBIC)\n",
    "    buf = io.BytesIO()\n",
    "    img.save(buf, format=\"JPEG\", quality=COMPACT_JPEG_Q, optimize=True)\n",
    "    b64 = base64.b64encode(buf.getvalue()).decode(\"ascii\")\n",
    "    return \"data:image/jpeg;base64,\" + b64\n",
    "\n",
    "def request_json(url: str, payload: dict, timeout: int, retry: int) -> dict:\n",
    "    last_e = None\n",
    "    for _ in range(retry + 1):\n",
    "        try:\n",
    "            r = requests.post(url, json=payload, timeout=timeout)\n",
    "            r.raise_for_status()\n",
    "            return r.json()\n",
    "        except Exception as <LOCAL_DRIVE_E>\n",
    "            last_e = e\n",
    "            time.sleep(0.5)\n",
    "    raise last_e\n",
    "\n",
    "def normalize_decision(x: str) -> str:\n",
    "    # normalize to ACCEPT/REJECT/AMBIGUOUS\n",
    "    if x is None:\n",
    "        return \"AMBIGUOUS\"\n",
    "    t = str(x).strip().upper()\n",
    "    if t in (\"ACCEPT\", \"REJECT\", \"AMBIGUOUS\"):\n",
    "        return t\n",
    "    # tolerate some variants\n",
    "    if \"ACCEPT\" in t: return \"ACCEPT\"\n",
    "    if \"REJECT\" in t: return \"REJECT\"\n",
    "    return \"AMBIGUOUS\""
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "ad281721-bebd-402f-869c-039c261fc0c0",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] mother_U rows: 80431\n",
      "[INFO] sample size: 4294\n",
      "[OUT] wrote sample -> <FULL_PRF_ROOT>\\YL\\HXYZ\\sample_pairs_stratified_v1.jsonl\n",
      "[OUT] sample breakdown: AUTO~ 2000 DISPUTE~ 2294 STRONGC~ 313\n"
     ]
    }
   ],
   "source": [
    "def load_mother_u(path: Path) -> List[dict]:\n",
    "    rows = []\n",
    "    with path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            rows.append(json.loads(line))\n",
    "    return rows\n",
    "\n",
    "def build_stratified_sample(rows: List[dict], seed: int) -> List[dict]:\n",
    "    rng = random.Random(seed)\n",
    "\n",
    "    auto = []\n",
    "    dispute = []\n",
    "    strongc = []\n",
    "\n",
    "    for j in rows:\n",
    "        src = j.get(\"final_source\")\n",
    "        if src == \"AUTO_2OF3\":\n",
    "            auto.append(j)\n",
    "        elif src == \"TEACHER_30B\":\n",
    "            dispute.append(j)\n",
    "\n",
    "        # strong-C identification\n",
    "        fd = bool(j.get(\"force_dispute\", False))\n",
    "        delta = None\n",
    "        try:\n",
    "            # mother_U has C: {\"noise\":..., \"delta\":..., \"decision\":...}\n",
    "            delta = float(j.get(\"C\", {}).get(\"delta\"))\n",
    "        except Exception:\n",
    "            delta = None\n",
    "        if fd or (delta is not None and delta <= DELTA_STRONG):\n",
    "            strongc.append(j)\n",
    "\n",
    "    # sample AUTO/DISPUTE\n",
    "    rng.shuffle(auto)\n",
    "    rng.shuffle(dispute)\n",
    "\n",
    "    auto_s = auto[:min(N_AUTO, len(auto))]\n",
    "    dis_s = dispute[:min(N_DISPUTE, len(dispute))]\n",
    "\n",
    "    # strong-C all (optionally)\n",
    "    if INCLUDE_STRONGC_ALL:\n",
    "        # keep all strong-C, but remove duplicates that already in auto_s/dis_s\n",
    "        seen = set(key_of(x[\"query_image_id\"], x[\"candidate_image_id\"]) for x in (auto_s + dis_s))\n",
    "        strong_s = []\n",
    "        for x in strongc:\n",
    "            k = key_of(x[\"query_image_id\"], x[\"candidate_image_id\"])\n",
    "            if k not in seen:\n",
    "                strong_s.append(x)\n",
    "        sample = auto_s + dis_s + strong_s\n",
    "    else:\n",
    "        sample = auto_s + dis_s\n",
    "\n",
    "    # finalize minimal record for experiment (store PRF decision but don't alter source)\n",
    "    out = []\n",
    "    for x in sample:\n",
    "        out.append({\n",
    "            \"schema\": \"core_sample_v1\",\n",
    "            \"query_image_id\": int(x[\"query_image_id\"]),\n",
    "            \"candidate_image_id\": int(x[\"candidate_image_id\"]),\n",
    "            \"query_path\": x[\"query_path\"],\n",
    "            \"candidate_path\": x[\"candidate_path\"],\n",
    "            \"prf_final_decision\": normalize_decision(x.get(\"final_decision\")),\n",
    "            \"prf_final_source\": x.get(\"final_source\"),\n",
    "            \"force_dispute\": bool(x.get(\"force_dispute\", False)),\n",
    "            \"c_delta\": x.get(\"C\", {}).get(\"delta\", None),\n",
    "        })\n",
    "\n",
    "    rng.shuffle(out)  # shuffle evaluation order\n",
    "    return out\n",
    "\n",
    "rows = load_mother_u(MOTHER_U)\n",
    "print(\"[INFO] mother_U rows:\", len(rows))\n",
    "\n",
    "sample = build_stratified_sample(rows, SEED)\n",
    "print(\"[INFO] sample size:\", len(sample))\n",
    "\n",
    "# write sample jsonl (overwrite OK: deterministic by seed)\n",
    "with SAMPLE_JSONL.open(\"w\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "    for j in sample:\n",
    "        f.write(json.dumps(j, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "print(\"[OUT] wrote sample ->\", SAMPLE_JSONL)\n",
    "print(\"[OUT] sample breakdown:\",\n",
    "      \"AUTO~\", sum(1 for x in sample if x[\"prf_final_source\"]==\"AUTO_2OF3\"),\n",
    "      \"DISPUTE~\", sum(1 for x in sample if x[\"prf_final_source\"]==\"TEACHER_30B\"),\n",
    "      \"STRONGC~\", sum(1 for x in sample if (x[\"force_dispute\"] or (x[\"c_delta\"] is not None and float(x[\"c_delta\"])<=DELTA_STRONG))))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "id": "15dac93c-1baa-4856-bc70-b286da136edf",
   "metadata": {},
   "outputs": [],
   "source": [
    "DIRECT30B_SYSTEM = (\n",
    "    \"你是一个严格的图像配对质量评估器。\"\n",
    "    \"你的任务是判断两张图像是否适合作为 image-to-image 训练配对。\"\n",
    "    \"你必须输出严格 JSON。\"\n",
    ")\n",
    "\n",
    "DIRECT30B_USER = \"\"\"\n",
    "请判断给定的两张图像是否适合作为 image-to-image 训练配对。\n",
    "注意：允许存在轻微噪声或局部覆盖，但若会误导训练则应拒绝。\n",
    "\n",
    "只输出严格 JSON（不要 Markdown，不要多余文本）：\n",
    "{\n",
    "  \"schema\": \"direct30b_pair_quality_v1\",\n",
    "  \"final_decision\": \"ACCEPT | REJECT | AMBIGUOUS\",\n",
    "  \"confidence\": 0.0,\n",
    "  \"reason\": \"中文一句话说明核心理由\"\n",
    "}\n",
    "\"\"\".strip()\n",
    "\n",
    "def call_direct30b(q_path: str, c_path: str) -> dict:\n",
    "    q = img_to_data_url(q_path)\n",
    "    c = img_to_data_url(c_path)\n",
    "\n",
    "    content = [\n",
    "        {\"type\": \"text\", \"text\": DIRECT30B_USER},\n",
    "        {\"type\": \"text\", \"text\": \"图像1（query）：\"},\n",
    "        {\"type\": \"image_url\", \"image_url\": {\"url\": q}},\n",
    "        {\"type\": \"text\", \"text\": \"图像2（candidate）：\"},\n",
    "        {\"type\": \"image_url\", \"image_url\": {\"url\": c}},\n",
    "    ]\n",
    "    payload = {\n",
    "        \"model\": MODEL_30B,\n",
    "        \"messages\": [\n",
    "            {\"role\": \"system\", \"content\": DIRECT30B_SYSTEM},\n",
    "            {\"role\": \"user\", \"content\": content},\n",
    "        ],\n",
    "        \"temperature\": TEMP_30B,\n",
    "    }\n",
    "    j = request_json(LLM_30B_URL, payload, TIMEOUT_30B, RETRY_30B)\n",
    "    msg = j[\"choices\"][0][\"message\"][\"content\"]\n",
    "    obj = extract_json(msg)\n",
    "\n",
    "    if obj.get(\"schema\") != \"direct30b_pair_quality_v1\":\n",
    "        raise ValueError(f\"bad schema: {obj.get('schema')}\")\n",
    "    dec = normalize_decision(obj.get(\"final_decision\"))\n",
    "    conf = float(obj.get(\"confidence\", 0.0))\n",
    "    if not (0.0 <= conf <= 1.0):\n",
    "        raise ValueError(f\"bad confidence: {conf}\")\n",
    "    if not isinstance(obj.get(\"reason\"), str) or len(obj[\"reason\"].strip()) == 0:\n",
    "        raise ValueError(\"bad reason\")\n",
    "    obj[\"final_decision\"] = dec\n",
    "    obj[\"confidence\"] = conf\n",
    "    obj[\"reason\"] = obj[\"reason\"].strip()\n",
    "    return obj"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "id": "44e3b034-5860-415e-b714-16bf2db81235",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[RESUME] done: 0 | DONE_TXT: <FULL_PRF_ROOT>\\YL\\HXYZ\\direct30b_done_pairs.txt\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Direct30B baseline: 100%|███████████████████████████████████████| 4294/4294 [52:43<00:00,  1.36it/s]"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[OUT] pred -> <FULL_PRF_ROOT>\\YL\\HXYZ\\direct30b_pred_v1.jsonl\n",
      "[OUT] done -> <FULL_PRF_ROOT>\\YL\\HXYZ\\direct30b_done_pairs.txt\n",
      "[OUT] fail -> <FULL_PRF_ROOT>\\YL\\HXYZ\\direct30b_failed_v1.jsonl\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "\n"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# Cell 4 — Run Direct 30B (Resume + Progress + Fail-log)\n",
    "# ============================================================\n",
    "\n",
    "def iter_sample(path: Path):\n",
    "    with path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if line.strip():\n",
    "                yield json.loads(line)\n",
    "\n",
    "done = read_done_set(DONE_TXT)\n",
    "print(\"[RESUME] done:\", len(done), \"| DONE_TXT:\", DONE_TXT)\n",
    "\n",
    "# count total\n",
    "total = 0\n",
    "with SAMPLE_JSONL.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "    for line in <LOCAL_DRIVE_F>\n",
    "        if line.strip():\n",
    "            total += 1\n",
    "\n",
    "pbar = tqdm(total=total, desc=\"Direct30B baseline\", ncols=100)\n",
    "\n",
    "try:\n",
    "    with PRED_JSONL.open(\"a\", encoding=\"utf-8\") as fw:\n",
    "        for item in iter_sample(SAMPLE_JSONL):\n",
    "\n",
    "            qid = int(item[\"query_image_id\"])\n",
    "            cid = int(item[\"candidate_image_id\"])\n",
    "            k = key_of(qid, cid)\n",
    "\n",
    "            if RESUME and k in done:\n",
    "                pbar.update(1)\n",
    "                continue\n",
    "\n",
    "            try:\n",
    "                pred = call_direct30b(\n",
    "                    item[\"query_path\"],\n",
    "                    item[\"candidate_path\"]\n",
    "                )\n",
    "\n",
    "                out = {\n",
    "                    \"schema\": \"direct30b_pred_v1\",\n",
    "                    \"query_image_id\": qid,\n",
    "                    \"candidate_image_id\": cid,\n",
    "                    \"query_path\": item[\"query_path\"],\n",
    "                    \"candidate_path\": item[\"candidate_path\"],\n",
    "                    \"direct30b\": pred,\n",
    "                    \"prf_final_decision\": item[\"prf_final_decision\"],\n",
    "                    \"prf_final_source\": item[\"prf_final_source\"],\n",
    "                    \"force_dispute\": bool(item.get(\"force_dispute\", False)),\n",
    "                    \"c_delta\": item.get(\"c_delta\", None),\n",
    "                    \"timestamp\": now_iso(),\n",
    "                }\n",
    "\n",
    "                fw.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "                append_done(DONE_TXT, k)\n",
    "                done.add(k)\n",
    "\n",
    "            except Exception as <LOCAL_DRIVE_E>\n",
    "                append_fail(FAIL_JSONL, {\n",
    "                    \"when\": now_iso(),\n",
    "                    \"stage\": \"DIRECT30B\",\n",
    "                    \"key\": k,\n",
    "                    \"query_path\": item[\"query_path\"],\n",
    "                    \"candidate_path\": item[\"candidate_path\"],\n",
    "                    \"error\": str(e),\n",
    "                })\n",
    "\n",
    "            pbar.update(1)\n",
    "\n",
    "finally:\n",
    "    pbar.close()\n",
    "\n",
    "print(\"[OUT] pred ->\", PRED_JSONL)\n",
    "print(\"[OUT] done ->\", DONE_TXT)\n",
    "print(\"[OUT] fail ->\", FAIL_JSONL)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "id": "43a0cb82-edbc-4999-bd8a-0f6f58c10631",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] loaded preds: 4294\n",
      "[OUT] metrics -> <FULL_PRF_ROOT>\\YL\\HXYZ\\core_metrics_v1.json\n",
      "[OUT] metrics -> <FULL_PRF_ROOT>\\YL\\HXYZ\\core_metrics_v1.csv\n",
      "\n",
      "[CORE RESULTS]\n",
      "OVERALL agree_rate: 0.6772240335351654\n",
      "AUTO    agree_rate: 0.8545\n",
      "DISPUTE agree_rate: 0.522667829119442\n",
      "STRONGC agree_rate: 0.8626198083067093\n"
     ]
    }
   ],
   "source": [
    "def load_preds(path: Path) -> List[dict]:\n",
    "    rows = []\n",
    "    if not path.exists():\n",
    "        return rows\n",
    "    with path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if line.strip():\n",
    "                rows.append(json.loads(line))\n",
    "    return rows\n",
    "\n",
    "preds = load_preds(PRED_JSONL)\n",
    "print(\"[INFO] loaded preds:\", len(preds))\n",
    "\n",
    "def subset_tag(x: dict) -> str:\n",
    "    src = x.get(\"prf_final_source\")\n",
    "    if src == \"AUTO_2OF3\":\n",
    "        return \"AUTO\"\n",
    "    if src == \"TEACHER_30B\":\n",
    "        return \"DISPUTE\"\n",
    "    return \"OTHER\"\n",
    "\n",
    "def is_strongc(x: dict) -> bool:\n",
    "    if bool(x.get(\"force_dispute\", False)):\n",
    "        return True\n",
    "    try:\n",
    "        d = x.get(\"c_delta\", None)\n",
    "        if d is None:\n",
    "            return False\n",
    "        return float(d) <= DELTA_STRONG\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "def compute_agreement(rows: List[dict]) -> dict:\n",
    "    n = len(rows)\n",
    "    if n == 0:\n",
    "        return {\"n\": 0, \"agree\": 0, \"agree_rate\": None, \"dist_prf\": {}, \"dist_direct\": {}}\n",
    "\n",
    "    dist_prf = {\"ACCEPT\":0,\"REJECT\":0,\"AMBIGUOUS\":0}\n",
    "    dist_direct = {\"ACCEPT\":0,\"REJECT\":0,\"AMBIGUOUS\":0}\n",
    "    agree = 0\n",
    "\n",
    "    for r in rows:\n",
    "        prf = normalize_decision(r.get(\"prf_final_decision\"))\n",
    "        direct = normalize_decision(r.get(\"direct30b\", {}).get(\"final_decision\"))\n",
    "        dist_prf[prf] += 1\n",
    "        dist_direct[direct] += 1\n",
    "        if prf == direct:\n",
    "            agree += 1\n",
    "\n",
    "    return {\n",
    "        \"n\": n,\n",
    "        \"agree\": agree,\n",
    "        \"agree_rate\": agree / n,\n",
    "        \"dist_prf\": dist_prf,\n",
    "        \"dist_direct\": dist_direct,\n",
    "    }\n",
    "\n",
    "overall = compute_agreement(preds)\n",
    "auto_rows = [x for x in preds if subset_tag(x) == \"AUTO\"]\n",
    "dispute_rows = [x for x in preds if subset_tag(x) == \"DISPUTE\"]\n",
    "strong_rows = [x for x in preds if is_strongc(x)]\n",
    "\n",
    "metrics = {\n",
    "    \"schema\": \"core_metrics_v1\",\n",
    "    \"timestamp\": now_iso(),\n",
    "    \"inputs\": {\n",
    "        \"mother_U\": str(MOTHER_U),\n",
    "        \"sample_jsonl\": str(SAMPLE_JSONL),\n",
    "        \"pred_jsonl\": str(PRED_JSONL),\n",
    "        \"seed\": SEED,\n",
    "        \"N_AUTO\": N_AUTO,\n",
    "        \"N_DISPUTE\": N_DISPUTE,\n",
    "        \"INCLUDE_STRONGC_ALL\": INCLUDE_STRONGC_ALL,\n",
    "        \"DELTA_STRONG\": DELTA_STRONG,\n",
    "    },\n",
    "    \"overall\": overall,\n",
    "    \"by_subset\": {\n",
    "        \"AUTO\": compute_agreement(auto_rows),\n",
    "        \"DISPUTE\": compute_agreement(dispute_rows),\n",
    "        \"STRONGC\": compute_agreement(strong_rows),\n",
    "    }\n",
    "}\n",
    "\n",
    "with METRICS_JSON.open(\"w\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "    json.dump(metrics, f, ensure_ascii=False, indent=2)\n",
    "\n",
    "# also write a simple CSV table\n",
    "import csv\n",
    "with METRICS_CSV.open(\"w\", encoding=\"utf-8\", newline=\"\") as <LOCAL_DRIVE_F>\n",
    "    w = csv.writer(f)\n",
    "    w.writerow([\"subset\",\"n\",\"agree\",\"agree_rate\",\"prf_ACCEPT\",\"prf_REJECT\",\"prf_AMBIGUOUS\",\"direct_ACCEPT\",\"direct_REJECT\",\"direct_AMBIGUOUS\"])\n",
    "    for name, stat in [(\"OVERALL\", metrics[\"overall\"]),\n",
    "                       (\"AUTO\", metrics[\"by_subset\"][\"AUTO\"]),\n",
    "                       (\"DISPUTE\", metrics[\"by_subset\"][\"DISPUTE\"]),\n",
    "                       (\"STRONGC\", metrics[\"by_subset\"][\"STRONGC\"])]:\n",
    "        dist_p = stat[\"dist_prf\"] if stat[\"dist_prf\"] else {\"ACCEPT\":0,\"REJECT\":0,\"AMBIGUOUS\":0}\n",
    "        dist_d = stat[\"dist_direct\"] if stat[\"dist_direct\"] else {\"ACCEPT\":0,\"REJECT\":0,\"AMBIGUOUS\":0}\n",
    "        w.writerow([name, stat[\"n\"], stat[\"agree\"], stat[\"agree_rate\"],\n",
    "                    dist_p[\"ACCEPT\"], dist_p[\"REJECT\"], dist_p[\"AMBIGUOUS\"],\n",
    "                    dist_d[\"ACCEPT\"], dist_d[\"REJECT\"], dist_d[\"AMBIGUOUS\"]])\n",
    "\n",
    "print(\"[OUT] metrics ->\", METRICS_JSON)\n",
    "print(\"[OUT] metrics ->\", METRICS_CSV)\n",
    "\n",
    "print(\"\\n[CORE RESULTS]\")\n",
    "print(\"OVERALL agree_rate:\", metrics[\"overall\"][\"agree_rate\"])\n",
    "print(\"AUTO    agree_rate:\", metrics[\"by_subset\"][\"AUTO\"][\"agree_rate\"])\n",
    "print(\"DISPUTE agree_rate:\", metrics[\"by_subset\"][\"DISPUTE\"][\"agree_rate\"])\n",
    "print(\"STRONGC agree_rate:\", metrics[\"by_subset\"][\"STRONGC\"][\"agree_rate\"])"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "bbe362f3-29e1-4a3c-8ec4-0f0b6877b42d",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] disagreements: 1386\n",
      "[OUT] disagreements -> <FULL_PRF_ROOT>\\YL\\HXYZ\\disagreements_sample_v1.jsonl\n"
     ]
    }
   ],
   "source": [
    "# export disagreements (optionally cap to avoid huge)\n",
    "MAX_DISAGREE_EXPORT = 500\n",
    "\n",
    "dis = []\n",
    "for r in preds:\n",
    "    prf = normalize_decision(r.get(\"prf_final_decision\"))\n",
    "    direct = normalize_decision(r.get(\"direct30b\", {}).get(\"final_decision\"))\n",
    "    if prf != direct:\n",
    "        dis.append(r)\n",
    "\n",
    "print(\"[INFO] disagreements:\", len(dis))\n",
    "\n",
    "# shuffle and cap\n",
    "random.Random(SEED).shuffle(dis)\n",
    "dis = dis[:min(MAX_DISAGREE_EXPORT, len(dis))]\n",
    "\n",
    "with DISAGREE_JSONL.open(\"w\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "    for r in dis:\n",
    "        # keep minimal fields for audit\n",
    "        out = {\n",
    "            \"schema\": \"disagreement_case_v1\",\n",
    "            \"query_image_id\": r[\"query_image_id\"],\n",
    "            \"candidate_image_id\": r[\"candidate_image_id\"],\n",
    "            \"query_path\": r[\"query_path\"],\n",
    "            \"candidate_path\": r[\"candidate_path\"],\n",
    "            \"prf_final_decision\": r[\"prf_final_decision\"],\n",
    "            \"prf_final_source\": r[\"prf_final_source\"],\n",
    "            \"direct30b_final_decision\": r[\"direct30b\"][\"final_decision\"],\n",
    "            \"direct30b_confidence\": r[\"direct30b\"][\"confidence\"],\n",
    "            \"direct30b_reason\": r[\"direct30b\"][\"reason\"],\n",
    "            \"force_dispute\": r.get(\"force_dispute\", False),\n",
    "            \"c_delta\": r.get(\"c_delta\", None),\n",
    "        }\n",
    "        f.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "print(\"[OUT] disagreements ->\", DISAGREE_JSONL)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 8,
   "id": "f8ef4693-1fb2-46f0-ac02-cd4370bbacd7",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] preds: 4294\n",
      "[INFO] disagreements: 500\n",
      "\n",
      "[OVERALL decision dist]\n",
      "PRF   : Counter({'REJECT': 2268, 'ACCEPT': 1442, 'AMBIGUOUS': 584})\n",
      "Direct: Counter({'ACCEPT': 2596, 'REJECT': 1698})\n",
      "\n",
      "[DISAGREEMENT matrix (PRF -> Direct)] top10\n",
      "('REJECT', 'ACCEPT') 256\n",
      "('AMBIGUOUS', 'ACCEPT') 187\n",
      "('AMBIGUOUS', 'REJECT') 31\n",
      "('ACCEPT', 'REJECT') 26\n",
      "\n",
      "[DISAGREEMENT summary]\n",
      "PRF ACCEPT but Direct REJECT: 26 (0.052)\n",
      "PRF REJECT but Direct ACCEPT: 256 (0.512)\n",
      "Any AMBIGUOUS involved       : 218 (0.436)\n",
      "\n",
      "[DISAGREEMENT by subset]\n",
      "AUTO n= 100 | A->R 0.000 | R->A 1.000 | anyAmb 0.000\n",
      "DISPUTE n= 400 | A->R 0.065 | R->A 0.390 | anyAmb 0.545\n",
      "\n",
      "[STRONGC disagreements] 11 (0.022 of all disagreements)\n"
     ]
    }
   ],
   "source": [
    "from pathlib import Path\n",
    "import json, math, random\n",
    "from collections import Counter, defaultdict\n",
    "\n",
    "OUT_DIR = Path(r\"<FULL_PRF_ROOT>\\YL\\HXYZ\")\n",
    "PRED_JSONL = OUT_DIR / \"direct30b_pred_v1.jsonl\"\n",
    "DISAGREE_JSONL = OUT_DIR / \"disagreements_sample_v1.jsonl\"\n",
    "\n",
    "assert PRED_JSONL.exists(), PRED_JSONL\n",
    "assert DISAGREE_JSONL.exists(), DISAGREE_JSONL\n",
    "\n",
    "def load_jsonl(p: Path):\n",
    "    rows = []\n",
    "    with p.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if line.strip():\n",
    "                rows.append(json.loads(line))\n",
    "    return rows\n",
    "\n",
    "preds = load_jsonl(PRED_JSONL)\n",
    "dis = load_jsonl(DISAGREE_JSONL)\n",
    "\n",
    "print(\"[INFO] preds:\", len(preds))\n",
    "print(\"[INFO] disagreements:\", len(dis))\n",
    "\n",
    "def norm(x):\n",
    "    t = str(x).strip().upper()\n",
    "    if t in (\"ACCEPT\",\"REJECT\",\"AMBIGUOUS\"):\n",
    "        return t\n",
    "    if \"ACCEPT\" in t: return \"ACCEPT\"\n",
    "    if \"REJECT\" in t: return \"REJECT\"\n",
    "    return \"AMBIGUOUS\"\n",
    "\n",
    "def subset_tag(r):\n",
    "    s = r.get(\"prf_final_source\")\n",
    "    if s == \"AUTO_2OF3\": return \"AUTO\"\n",
    "    if s == \"TEACHER_30B\": return \"DISPUTE\"\n",
    "    return \"OTHER\"\n",
    "\n",
    "def is_strongc(r, delta_strong=-0.2):\n",
    "    if bool(r.get(\"force_dispute\", False)): return True\n",
    "    d = r.get(\"c_delta\", None)\n",
    "    try:\n",
    "        return d is not None and float(d) <= delta_strong\n",
    "    except Exception:\n",
    "        return False\n",
    "\n",
    "# overall decision distribution\n",
    "dist_prf = Counter()\n",
    "dist_direct = Counter()\n",
    "for r in preds:\n",
    "    dist_prf[norm(r[\"prf_final_decision\"])] += 1\n",
    "    dist_direct[norm(r[\"direct30b\"][\"final_decision\"])] += 1\n",
    "\n",
    "print(\"\\n[OVERALL decision dist]\")\n",
    "print(\"PRF   :\", dist_prf)\n",
    "print(\"Direct:\", dist_direct)\n",
    "\n",
    "# disagreement type matrix\n",
    "mat = Counter()\n",
    "mat_by_subset = defaultdict(Counter)\n",
    "for r in dis:\n",
    "    p = norm(r[\"prf_final_decision\"])\n",
    "    d = norm(r[\"direct30b_final_decision\"])\n",
    "    tag = subset_tag(r)\n",
    "    mat[(p,d)] += 1\n",
    "    mat_by_subset[tag][(p,d)] += 1\n",
    "\n",
    "print(\"\\n[DISAGREEMENT matrix (PRF -> Direct)] top10\")\n",
    "for (k,v) in mat.most_common(10):\n",
    "    print(k, v)\n",
    "\n",
    "print(\"\\n[DISAGREEMENT summary]\")\n",
    "tot = len(dis)\n",
    "a = sum(v for (p,d),v in mat.items() if p==\"ACCEPT\" and d==\"REJECT\")\n",
    "b = sum(v for (p,d),v in mat.items() if p==\"REJECT\" and d==\"ACCEPT\")\n",
    "c = sum(v for (p,d),v in mat.items() if p==\"AMBIGUOUS\" or d==\"AMBIGUOUS\")\n",
    "print(\"PRF ACCEPT but Direct REJECT:\", a, f\"({a/tot:.3f})\")\n",
    "print(\"PRF REJECT but Direct ACCEPT:\", b, f\"({b/tot:.3f})\")\n",
    "print(\"Any AMBIGUOUS involved       :\", c, f\"({c/tot:.3f})\")\n",
    "\n",
    "print(\"\\n[DISAGREEMENT by subset]\")\n",
    "for tag in [\"AUTO\",\"DISPUTE\",\"OTHER\"]:\n",
    "    sub_tot = sum(mat_by_subset[tag].values())\n",
    "    if sub_tot == 0:\n",
    "        continue\n",
    "    a2 = sum(v for (p,d),v in mat_by_subset[tag].items() if p==\"ACCEPT\" and d==\"REJECT\")\n",
    "    b2 = sum(v for (p,d),v in mat_by_subset[tag].items() if p==\"REJECT\" and d==\"ACCEPT\")\n",
    "    c2 = sum(v for (p,d),v in mat_by_subset[tag].items() if p==\"AMBIGUOUS\" or d==\"AMBIGUOUS\")\n",
    "    print(tag, \"n=\", sub_tot,\n",
    "          \"| A->R\", f\"{a2/sub_tot:.3f}\",\n",
    "          \"| R->A\", f\"{b2/sub_tot:.3f}\",\n",
    "          \"| anyAmb\", f\"{c2/sub_tot:.3f}\")\n",
    "\n",
    "# strongC specific\n",
    "strong_dis = [r for r in dis if is_strongc(r)]\n",
    "print(\"\\n[STRONGC disagreements]\", len(strong_dis), f\"({len(strong_dis)/len(dis):.3f} of all disagreements)\")"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "49d170b8-abfb-4c84-b9b1-e177035cb5ee",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "rtx5090_final (CUDA13.1)",
   "language": "python",
   "name": "rtx5090_final"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
