{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "28c4ceb2-9bcb-4a31-8680-298544f1eb61",
   "metadata": {},
   "outputs": [
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "<LOCAL_USER_HOME>\\.conda\\envs\\rtx5090_final\\lib\\site-packages\\tqdm\\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html\n",
      "  from .autonotebook import tqdm as notebook_tqdm\n",
      "W0203 17:57:17.391000 9672 site-packages\\torch\\distributed\\elastic\\multiprocessing\\redirects.py:29] NOTE: Redirects are currently not supported in Windows or MacOs.\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[INFO] 2026-02-03T17:57:17 | loaded manifest N_IMG=10000\n",
      "[INFO] using OUT_DIR=<FULL_PRF_ROOT>\\abcpipeline_full\n",
      "[INFO] MAX_PAIRS=None RESUME=True FAIL_FAST_GLOBAL=False\n",
      "[RUN] Stage A...\n",
      "[A] resume done=0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Step A (sim+rank): 80693it [00:03, 20245.46it/s]\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "[A] done -> <FULL_PRF_ROOT>\\abcpipeline_full\\a_clip_pairs_v1.jsonl\n",
      "[RUN] Stage B...\n",
      "[B] resume done=0\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Teacher 30B (disputes):  84%|████████████████████████▍    | 39756/47144 [8:56:58<1:36:25,  1.28it/s]"
     ]
    }
   ],
   "source": [
    "# ============================================================\n",
    "# PRF Full Pipeline (Merged Script) — A/B/C + Merge + D + U + run_summary.json\n",
    "# Target: <FULL_PRF_ROOT>\\abcpipeline_full\n",
    "# Notes:\n",
    "# - Supports RESUME (pair-level) for long runs\n",
    "# - \"Controlled landing\": all failures are written to *_failed.jsonl; pipeline continues\n",
    "#   (You can set FAIL_FAST_GLOBAL=True to stop at first failure)\n",
    "# - Offline CLIP only (local_files_only=True); no HF download\n",
    "# - 8B/30B via llama.cpp HTTP endpoints (8080/8081)\n",
    "# ============================================================\n",
    "\n",
    "import os, re, io, json, time, math, base64, hashlib\n",
    "from pathlib import Path\n",
    "from dataclasses import dataclass\n",
    "from typing import Dict, Tuple, List, Optional, Any\n",
    "\n",
    "import numpy as np\n",
    "from PIL import Image, ImageDraw\n",
    "from tqdm import tqdm\n",
    "import requests\n",
    "\n",
    "import torch\n",
    "from transformers import CLIPModel, CLIPProcessor\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 0) CONFIG (EDIT HERE)\n",
    "# =========================\n",
    "ROOT = Path(r\"<FULL_PRF_ROOT>\")\n",
    "POOL_DIR  = ROOT / \"pool\"\n",
    "CACHE_DIR = ROOT / \"cache\"\n",
    "OUT_DIR   = ROOT / \"abcpipeline_full\"  # <-- full run output\n",
    "OUT_DIR.mkdir(parents=True, exist_ok=True)\n",
    "\n",
    "# Inputs (from pool stage already finished)\n",
    "PAIRS_IN  = POOL_DIR / \"pairs_full_pool_v1.jsonl\"\n",
    "MANIFEST  = POOL_DIR / \"manifest_all_images.jsonl\"\n",
    "CLIP_MMP  = CACHE_DIR / \"clip_L14_gallery_emb.f16.mmp\"  # gallery embedding cache\n",
    "\n",
    "# Offline CLIP dir (frozen)\n",
    "LOCAL_CLIP_DIR = Path(r\"<PRF_CHECKPOINT_ROOT>\\cache\\hf\\openai\\clip-vit-large-patch14\")\n",
    "\n",
    "# 8B / 30B endpoints\n",
    "LLM_8B_URL  = \"http://127.0.0.1:8080/v1/chat/completions\"\n",
    "LLM_30B_URL = \"http://127.0.0.1:8081/v1/chat/completions\"\n",
    "MODEL_8B  = \"qwen3-vl-8b\"\n",
    "MODEL_30B = \"qwen3-vl-30b\"\n",
    "\n",
    "# Long-run behavior\n",
    "MAX_PAIRS: Optional[int] = None  # None = full\n",
    "RESUME = True\n",
    "FAIL_FAST_GLOBAL = False  # True = stop immediately when any pair fails\n",
    "\n",
    "# Image compact for 8B\n",
    "COMPACT_LONG_SIDE = 768\n",
    "COMPACT_JPEG_Q    = 75\n",
    "\n",
    "# C params (frozen v4)\n",
    "MAX_POLY  = 3\n",
    "TAU_NOISE = 0.70\n",
    "TEMP_8B_POLY = 0.0\n",
    "\n",
    "COVER_CAP = 0.20\n",
    "DELTA_STRONG = -0.20  # C strong counter-evidence threshold\n",
    "\n",
    "# Voting policy\n",
    "# - 2-of-3 majority among normalized votes A/B/C -> auto final\n",
    "# - Gate: if C gives strong counter-evidence (YES + delta <= DELTA_STRONG) -> force dispute -> Teacher\n",
    "FORCE_DISPUTE_ON_C_STRONG = True\n",
    "\n",
    "# Runtime perf knobs\n",
    "BATCH_EMB = 64  # only used if we need local CLIP (Step C)\n",
    "TIMEOUT_8B = 300\n",
    "TIMEOUT_30B = 600\n",
    "RETRY_8B = 2\n",
    "RETRY_30B = 1\n",
    "\n",
    "# Output files\n",
    "A_OUT   = OUT_DIR / \"a_clip_pairs_v1.jsonl\"\n",
    "B_OUT   = OUT_DIR / \"b_pair_review_v3.jsonl\"\n",
    "C_OUT   = OUT_DIR / \"c_noise_maskclip_v4.jsonl\"\n",
    "MERGED  = OUT_DIR / \"merged_abc_votes_v1.jsonl\"\n",
    "DISPUTE = OUT_DIR / \"dispute_for_teacher_v1.jsonl\"\n",
    "T_OUT   = OUT_DIR / \"teacher_30b_full_v1.jsonl\"\n",
    "U_OUT   = OUT_DIR / \"mother_U_v1.jsonl\"\n",
    "SUMMARY = OUT_DIR / \"run_summary.json\"\n",
    "\n",
    "A_DONE = OUT_DIR / \"a_done_pairs.txt\"\n",
    "B_DONE = OUT_DIR / \"b_done_pairs.txt\"\n",
    "C_DONE = OUT_DIR / \"c_done_pairs.txt\"\n",
    "T_DONE = OUT_DIR / \"t_done_pairs.txt\"\n",
    "U_DONE = OUT_DIR / \"u_done_pairs.txt\"\n",
    "\n",
    "A_FAIL = OUT_DIR / \"a_failed.jsonl\"\n",
    "B_FAIL = OUT_DIR / \"b_failed.jsonl\"\n",
    "C_FAIL = OUT_DIR / \"c_failed.jsonl\"\n",
    "T_FAIL = OUT_DIR / \"t_failed.jsonl\"\n",
    "U_FAIL = OUT_DIR / \"u_failed.jsonl\"\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 1) Frozen Prompts (B/C/D)\n",
    "# =========================\n",
    "B_SYSTEM_PROMPT = (\n",
    "    \"你是一个图像配对审核专家。\"\n",
    "    \"你的任务不是判断两张图像是否完全相同，\"\n",
    "    \"而是判断它们是否值得作为训练配对使用。\"\n",
    "    \"你需要输出可解释、可审查的结构化判据，\"\n",
    "    \"并严格按照要求输出 JSON。\"\n",
    ")\n",
    "\n",
    "B_ANCHORS = \"\"\"\n",
    "评分锚点（0–5，整数）：\n",
    "0 = 完全不符合；\n",
    "1 = 极弱 / 几乎不支持；\n",
    "2 = 较弱 / 证据不足；\n",
    "3 = 中等 / 勉强可接受但存在明显疑点；\n",
    "4 = 较强 / 大体一致；\n",
    "5 = 极强 / 几乎可以确定。\n",
    "\"\"\".strip()\n",
    "\n",
    "B_USER_PROMPT = f\"\"\"\n",
    "{B_ANCHORS}\n",
    "\n",
    "请你对给定的两张图像进行【配对审核】，并只输出严格 JSON（不要 Markdown，不要 ```）。\n",
    "\n",
    "【配对审核的目标说明】\n",
    "- ACCEPT：两张图像在语义或结构上具有一致性，适合作为训练配对（允许存在一定噪声或差异）。\n",
    "- REJECT：两张图像存在明显不一致或噪声干扰，会误导训练。\n",
    "- AMBIGUOUS：证据不足或存在冲突，无法可靠判断，建议交由更强模型或人工复核。\n",
    "\n",
    "【输出 JSON schema（必须完全符合）】：\n",
    "{{\n",
    "  \"schema\": \"pair_review_v3\",\n",
    "  \"criteria\": {{\n",
    "    \"pixel_consistency\": {{ \"score\": 0, \"reason\": \"中文一句话，说明像素级外观是否一致（颜色、纹理、细节等）\" }},\n",
    "    \"same_base_image\": {{ \"score\": 0, \"reason\": \"中文一句话，判断是否来自同一底图或同一拍摄源\" }},\n",
    "    \"same_instance\": {{ \"score\": 0, \"reason\": \"中文一句话，判断是否为同一物理实例（同一对象/主体）\" }},\n",
    "    \"strong_structure\": {{ \"score\": 0, \"reason\": \"中文一句话，判断关键结构或布局是否高度一致\" }},\n",
    "    \"weak_structure\": {{ \"score\": 0, \"reason\": \"中文一句话，判断次要结构、背景或局部形态是否相似\" }}\n",
    "  }},\n",
    "  \"final_recommendation\": \"ACCEPT | REJECT | AMBIGUOUS\",\n",
    "  \"confidence\": 0.0,\n",
    "  \"final_reason\": \"中文一句话，总结你做出最终判断的核心理由\"\n",
    "}}\n",
    "\n",
    "【重要要求】：\n",
    "1) 每个维度必须给出 score（0–5 的整数）和 reason（中文一句话）；\n",
    "2) final_reason 必须是综合性的总结，不要简单重复某一个维度；\n",
    "3) confidence 取值范围为 0~1，表示你对最终判断的确信程度（非校准概率）；\n",
    "4) 只输出 JSON，不要输出任何额外文本。\n",
    "\"\"\".strip()\n",
    "\n",
    "C_SYSTEM_PROMPT = (\n",
    "    \"你是视觉审计专家。你必须先判断图像中是否存在【会干扰配对判断的】显式噪声。\"\n",
    "    \"噪声并非必然存在：若不确信它会影响相似度/结构判断，必须回答 NO，并返回空 polygons。\"\n",
    "    \"你只输出严格 JSON。\"\n",
    ")\n",
    "\n",
    "C_USER_PROMPT = f\"\"\"\n",
    "请先判断是否存在【会干扰配对判断的】显式噪声（YES/NO），再决定是否画噪声 polygon。\n",
    "\n",
    "规则：\n",
    "- 若 noise_decision=NO，polygons 必须是 []\n",
    "- 若 noise_decision=YES 但 noise_confidence < {TAU_NOISE}，也必须视为 NO\n",
    "- 只标注局部、可指认的噪声区域（如覆盖文字/水印/边框/局部伪结构）。\n",
    "  若噪声很小、远离主体或不影响判断，应返回 NO。\n",
    "- polygons 最多 {MAX_POLY} 个：优先覆盖最影响判断的区域，避免过度细分。\n",
    "- points 使用归一化坐标 [0,1]，每个 polygon 至少 3 个点；无需写闭合点。\n",
    "\n",
    "输出 JSON：\n",
    "{{\n",
    "  \"schema\": \"polygon_v4\",\n",
    "  \"noise_decision\": \"YES|NO\",\n",
    "  \"noise_confidence\": 0.0,\n",
    "  \"noise_type\": \"none|overlay_text|watermark|border|compression|unknown\",\n",
    "  \"polygons\": [\n",
    "    {{\"label\":\"noise\",\"points\":[[0.1,0.2],[...]],\"reason_zh\":\"一句中文理由\"}}\n",
    "  ],\n",
    "  \"reason_zh\": \"一句中文总结（说明为何 YES 或 NO）\"\n",
    "}}\n",
    "\"\"\".strip()\n",
    "\n",
    "D_SYSTEM_PROMPT = \"\"\"\n",
    "你是 PRF（Pair Review Filtering）系统中的终裁裁判（Teacher）。\n",
    "\n",
    "在你接收到该样本之前，系统已经决定需要你参与仲裁。\n",
    "你不需要、也不应该关心该样本为何被送到你这里。\n",
    "\n",
    "A / B / C 子系统已经完成判断并提供显式证据。\n",
    "你的职责不是重新评审图像，而是仅基于这些证据进行最终裁决，\n",
    "并给出可解释的理由。\n",
    "\n",
    "禁止：\n",
    "- 重新独立评估图像\n",
    "- 重新生成五维度或噪声证据\n",
    "- 简单投票而不给出理由\n",
    "\"\"\".strip()\n",
    "\n",
    "# IMPORTANT: braces escaped for .format\n",
    "D_USER_TEMPLATE = \"\"\"\n",
    "这是 PRF 系统中的一个 image pair。\n",
    "A / B / C 已经给出了判断结果与显式证据（不同版本证据形式可能不同）。\n",
    "\n",
    "====================\n",
    "【A：CLIP 相似度证据】\n",
    "- A_decision: {A_decision}\n",
    "- A_score: {A_score}\n",
    "- A_rank: {A_rank}\n",
    "\n",
    "====================\n",
    "【B：8B 五维度评审】\n",
    "- pixel_consistency: {B_pixel}\n",
    "- same_base_image: {B_base}\n",
    "- same_instance: {B_instance}\n",
    "- strong_structure: {B_strong}\n",
    "- weak_structure: {B_weak}\n",
    "- B_final: {B_decision}\n",
    "- B_confidence: {B_conf}\n",
    "\n",
    "====================\n",
    "【C：Noise-aware 证据】\n",
    "- noise_detected: {C_noise}\n",
    "- cover_frac_raw: {C_cover_raw}\n",
    "- cover_frac_capped: {C_cover_cap}\n",
    "- mask_clip_raw: {C_clip_raw}\n",
    "- mask_clip_masked: {C_clip_masked}\n",
    "- mask_clip_delta: {C_delta}\n",
    "- C_decision: {C_decision}\n",
    "- C_explain: {C_explain}\n",
    "\n",
    "====================\n",
    "请基于以上证据进行仲裁，仅输出 JSON（不要 Markdown，不要多余文字）。\n",
    "\n",
    "输出 JSON：\n",
    "{{\n",
    "  \"schema\": \"prf_teacher_arbitration_v1\",\n",
    "  \"final_decision\": \"ACCEPT | REJECT | AMBIGUOUS\",\n",
    "  \"adopted_from\": [\"A\", \"B\", \"C\"],\n",
    "  \"overruled\": [\"A\", \"B\", \"C\"],\n",
    "  \"confidence\": 0.0,\n",
    "  \"reason\": \"中文一句话，说明你如何权衡证据\"\n",
    "}}\n",
    "\n",
    "规则（重要）：\n",
    "1) adopted_from：列出你最终判断主要依据的来源（通常 1~2 个）；\n",
    "2) overruled：列出与最终判断冲突、且被你否定的来源（可为空）；\n",
    "3) adopted_from 与 overruled 不应有交集；\n",
    "4) 若证据冲突：优先考虑 B 的结构一致性与 C 的 mask-clip delta（若 delta 显著），A 的 rank/score 用于支持或反证；\n",
    "5) confidence 为自评确信度（非校准概率），范围 0~1；\n",
    "6) 只输出 JSON。\n",
    "\"\"\".strip()\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 2) Helpers\n",
    "# =========================\n",
    "def now_iso():\n",
    "    return time.strftime(\"%Y-%m-%dT%H:%M:%S\", time.localtime())\n",
    "\n",
    "def key_of(qid: int, cid: int) -> str:\n",
    "    return f\"{qid}_{cid}\"\n",
    "\n",
    "def safe_int(x) -> int:\n",
    "    return int(x)  # handle numpy int32\n",
    "\n",
    "def safe_float(x) -> float:\n",
    "    return float(x)\n",
    "\n",
    "def sha1_short(s: str, n=10) -> str:\n",
    "    return hashlib.sha1(s.encode(\"utf-8\")).hexdigest()[:n]\n",
    "\n",
    "def read_done_set(done_path: Path) -> set:\n",
    "    if not (RESUME and done_path.exists()):\n",
    "        return set()\n",
    "    s = set()\n",
    "    with done_path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            t = line.strip()\n",
    "            if <LOCAL_DRIVE_T>\n",
    "                s.add(t)\n",
    "    return s\n",
    "\n",
    "def append_done(done_path: Path, k: str):\n",
    "    with done_path.open(\"a\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        f.write(k + \"\\n\")\n",
    "\n",
    "def append_fail(fail_path: Path, obj: dict):\n",
    "    with fail_path.open(\"a\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        f.write(json.dumps(obj, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "def extract_json(text: str) -> dict:\n",
    "    t = text.strip()\n",
    "    if t.startswith(\"{\") and t.endswith(\"}\"):\n",
    "        return json.loads(t)\n",
    "    m = re.search(r\"\\{[\\s\\S]*\\}\", t)\n",
    "    if not <LOCAL_DRIVE_M>\n",
    "        raise ValueError(\"No JSON object found\")\n",
    "    return json.loads(m.group(0))\n",
    "\n",
    "def img_to_data_url(path: str) -> str:\n",
    "    img = Image.open(path).convert(\"RGB\")\n",
    "    w, h = img.size\n",
    "    m = max(w, h)\n",
    "    if m > COMPACT_LONG_SIDE:\n",
    "        s = COMPACT_LONG_SIDE / m\n",
    "        img = img.resize((max(1, int(w*s)), max(1, int(h*s))), Image.BICUBIC)\n",
    "    buf = io.BytesIO()\n",
    "    img.save(buf, format=\"JPEG\", quality=COMPACT_JPEG_Q, optimize=True)\n",
    "    b64 = base64.b64encode(buf.getvalue()).decode(\"ascii\")\n",
    "    return \"data:image/jpeg;base64,\" + b64\n",
    "\n",
    "def request_json(url: str, payload: dict, timeout: int, retry: int) -> dict:\n",
    "    last_e = None\n",
    "    for _ in range(retry + 1):\n",
    "        try:\n",
    "            r = requests.post(url, json=payload, timeout=timeout)\n",
    "            r.raise_for_status()\n",
    "            return r.json()\n",
    "        except Exception as <LOCAL_DRIVE_E>\n",
    "            last_e = e\n",
    "            time.sleep(0.5)\n",
    "    raise last_e\n",
    "\n",
    "def validate_b(obj: dict):\n",
    "    if obj.get(\"schema\") != \"pair_review_v3\":\n",
    "        raise ValueError(f\"bad schema: {obj.get('schema')}\")\n",
    "    crit = obj[\"criteria\"]\n",
    "    for k in [\"pixel_consistency\",\"same_base_image\",\"same_instance\",\"strong_structure\",\"weak_structure\"]:\n",
    "        sc = crit[k][\"score\"]\n",
    "        if not (isinstance(sc, int) and 0 <= sc <= 5):\n",
    "            raise ValueError(f\"bad score {k}: {sc}\")\n",
    "        rz = crit[k][\"reason\"]\n",
    "        if not (isinstance(rz, str) and len(rz) > 0):\n",
    "            raise ValueError(f\"bad reason {k}\")\n",
    "    if obj[\"final_recommendation\"] not in [\"ACCEPT\",\"REJECT\",\"AMBIGUOUS\"]:\n",
    "        raise ValueError(\"bad final_recommendation\")\n",
    "    conf = obj[\"confidence\"]\n",
    "    if not (isinstance(conf, (int,float)) and 0 <= float(conf) <= 1):\n",
    "        raise ValueError(\"bad confidence\")\n",
    "    if not (isinstance(obj[\"final_reason\"], str) and len(obj[\"final_reason\"]) > 0):\n",
    "        raise ValueError(\"bad final_reason\")\n",
    "\n",
    "def validate_poly(obj: dict):\n",
    "    if obj.get(\"schema\") != \"polygon_v4\":\n",
    "        raise ValueError(f\"bad schema: {obj.get('schema')}\")\n",
    "    if obj[\"noise_decision\"] not in [\"YES\",\"NO\"]:\n",
    "        raise ValueError(\"bad noise_decision\")\n",
    "    conf = float(obj[\"noise_confidence\"])\n",
    "    if not (0 <= conf <= 1):\n",
    "        raise ValueError(\"bad noise_confidence\")\n",
    "    if obj[\"noise_type\"] not in [\"none\",\"overlay_text\",\"watermark\",\"border\",\"compression\",\"unknown\"]:\n",
    "        raise ValueError(\"bad noise_type\")\n",
    "    polys = obj[\"polygons\"]\n",
    "    if obj[\"noise_decision\"] == \"NO\" and polys != []:\n",
    "        raise ValueError(\"NO must have empty polygons\")\n",
    "    if not isinstance(obj[\"reason_zh\"], str) or len(obj[\"reason_zh\"]) == 0:\n",
    "        raise ValueError(\"bad reason_zh\")\n",
    "    if not isinstance(polys, list):\n",
    "        raise ValueError(\"bad polygons\")\n",
    "    if len(polys) > MAX_POLY:\n",
    "        raise ValueError(\"too many polygons\")\n",
    "    # points sanity (light)\n",
    "    for p in polys:\n",
    "        pts = p.get(\"points\", [])\n",
    "        if len(pts) < 3:\n",
    "            raise ValueError(\"polygon needs >=3 points\")\n",
    "\n",
    "def mask_image_with_polys(img: Image.Image, polys):\n",
    "    if not polys:\n",
    "        return img, 0.0\n",
    "    w, h = img.size\n",
    "    mask = Image.new(\"L\", (w, h), 0)\n",
    "    draw = ImageDraw.Draw(mask)\n",
    "    for poly in polys:\n",
    "        pts_xy = [(float(x)*w, float(y)*h) for x, y in poly[\"points\"]]\n",
    "        draw.polygon(pts_xy, fill=255)\n",
    "    out = img.copy()\n",
    "    out.paste((0,0,0), mask=mask)\n",
    "    cover = float(np.array(mask).mean()/255.0)\n",
    "    return out, cover\n",
    "\n",
    "def decide_A(sim: float) -> str:\n",
    "    if sim >= 0.90: return \"SUPPORT\"\n",
    "    if sim >= 0.80: return \"WEAK\"\n",
    "    return \"AGAINST\"\n",
    "\n",
    "def vote_from_A(a_dec: str) -> str:\n",
    "    if a_dec == \"SUPPORT\": return \"ACCEPT\"\n",
    "    if a_dec == \"AGAINST\": return \"REJECT\"\n",
    "    return \"AMBIGUOUS\"\n",
    "\n",
    "def vote_from_B(b_final: str) -> str:\n",
    "    return b_final\n",
    "\n",
    "def vote_from_C(c_obj: dict) -> str:\n",
    "    # C defaults neutral; only strong counter-evidence votes REJECT\n",
    "    if c_obj[\"C_decision\"] == \"REJECT\":\n",
    "        return \"REJECT\"\n",
    "    return \"AMBIGUOUS\"\n",
    "\n",
    "def two_of_three(v1: str, v2: str, v3: str) -> Optional[str]:\n",
    "    # Only return definite majority for ACCEPT/REJECT\n",
    "    cnt = { \"ACCEPT\":0, \"REJECT\":0, \"AMBIGUOUS\":0 }\n",
    "    for v in [v1,v2,v3]:\n",
    "        cnt[v] += 1\n",
    "    if cnt[\"ACCEPT\"] >= 2: return \"ACCEPT\"\n",
    "    if cnt[\"REJECT\"] >= 2: return \"REJECT\"\n",
    "    return None\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 3) Load Manifest + CLIP memmap\n",
    "# =========================\n",
    "assert PAIRS_IN.exists(), f\"Missing: {PAIRS_IN}\"\n",
    "assert MANIFEST.exists(), f\"Missing: {MANIFEST}\"\n",
    "assert CLIP_MMP.exists(), f\"Missing: {CLIP_MMP}\"\n",
    "assert LOCAL_CLIP_DIR.exists(), f\"Missing local CLIP dir: {LOCAL_CLIP_DIR}\"\n",
    "\n",
    "paths: List[str] = []\n",
    "with MANIFEST.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "    for line in <LOCAL_DRIVE_F>\n",
    "        j = json.loads(line)\n",
    "        paths.append(j[\"path\"])\n",
    "N_IMG = len(paths)\n",
    "\n",
    "emb = np.memmap(CLIP_MMP, dtype=\"float16\", mode=\"r\", shape=(N_IMG, 768))\n",
    "\n",
    "print(f\"[INFO] {now_iso()} | loaded manifest N_IMG={N_IMG}\")\n",
    "print(f\"[INFO] using OUT_DIR={OUT_DIR}\")\n",
    "print(f\"[INFO] MAX_PAIRS={MAX_PAIRS} RESUME={RESUME} FAIL_FAST_GLOBAL={FAIL_FAST_GLOBAL}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 4) Pair iterator\n",
    "# =========================\n",
    "def iter_pairs():\n",
    "    with PAIRS_IN.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for idx, line in enumerate(f):\n",
    "            if MAX_PAIRS is not None and idx >= MAX_PAIRS:\n",
    "                break\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            j = json.loads(line)\n",
    "            # normalize types\n",
    "            j[\"query_image_id\"] = safe_int(j[\"query_image_id\"])\n",
    "            j[\"candidate_image_id\"] = safe_int(j[\"candidate_image_id\"])\n",
    "            return_item = {\n",
    "                \"query_image_id\": j[\"query_image_id\"],\n",
    "                \"candidate_image_id\": j[\"candidate_image_id\"],\n",
    "                \"query_path\": j[\"query_path\"],\n",
    "                \"candidate_path\": j[\"candidate_path\"],\n",
    "            }\n",
    "            yield return_item\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 5) Step A: CLIP sim + rank (within each query)\n",
    "# =========================\n",
    "def step_A():\n",
    "    done = read_done_set(A_DONE)\n",
    "    print(f\"[A] resume done={len(done)}\")\n",
    "\n",
    "    # we need rank per-query; so buffer by query\n",
    "    cur_q = None\n",
    "    buf = []  # (item, sim)\n",
    "\n",
    "    def flush_buf(buf):\n",
    "        if not buf:\n",
    "            return 0\n",
    "        sims = np.array([s for _, s in buf], dtype=np.float32)\n",
    "        order = np.argsort(-sims)\n",
    "        ranks = np.empty_like(order)\n",
    "        ranks[order] = np.arange(1, len(buf)+1)\n",
    "\n",
    "        with A_OUT.open(\"a\", encoding=\"utf-8\") as fw, A_DONE.open(\"a\", encoding=\"utf-8\") as fd:\n",
    "            for i, (it, sim) in enumerate(buf):\n",
    "                k = key_of(it[\"query_image_id\"], it[\"candidate_image_id\"])\n",
    "                if RESUME and k in done:\n",
    "                    continue\n",
    "                out = {\n",
    "                    \"schema\": \"a_clip_pairs_v1\",\n",
    "                    \"query_image_id\": it[\"query_image_id\"],\n",
    "                    \"candidate_image_id\": it[\"candidate_image_id\"],\n",
    "                    \"query_path\": it[\"query_path\"],\n",
    "                    \"candidate_path\": it[\"candidate_path\"],\n",
    "                    \"clip_similarity\": safe_float(sim),\n",
    "                    \"A_decision\": decide_A(safe_float(sim)),\n",
    "                    \"A_rank\": safe_int(ranks[i]),\n",
    "                }\n",
    "                fw.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "                fd.write(k + \"\\n\")\n",
    "                done.add(k)\n",
    "        return len(buf)\n",
    "\n",
    "    pbar = tqdm(desc=\"Step A (sim+rank)\", total=(MAX_PAIRS if MAX_PAIRS else None), ncols=100)\n",
    "    try:\n",
    "        for it in iter_pairs():\n",
    "            qid, cid = it[\"query_image_id\"], it[\"candidate_image_id\"]\n",
    "            if cur_q is None:\n",
    "                cur_q = qid\n",
    "            if qid != cur_<LOCAL_DRIVE_Q>\n",
    "                flush_buf(buf)\n",
    "                buf = []\n",
    "                cur_q = qid\n",
    "\n",
    "            sim = float(np.dot(emb[qid].astype(np.float32), emb[cid].astype(np.float32)))\n",
    "            buf.append((it, sim))\n",
    "            pbar.update(1)\n",
    "        flush_buf(buf)\n",
    "    except Exception as <LOCAL_DRIVE_E>\n",
    "        append_fail(A_FAIL, {\"when\": now_iso(), \"stage\": \"A\", \"error\": str(e)})\n",
    "        if FAIL_FAST_GLOBAL:\n",
    "            raise\n",
    "    finally:\n",
    "        pbar.close()\n",
    "    print(f\"[A] done -> {A_OUT}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 6) Step B: 8B pair review (frozen prompt)\n",
    "# =========================\n",
    "def call_8b_pair_review(q_path: str, c_path: str) -> dict:\n",
    "    q = img_to_data_url(q_path)\n",
    "    c = img_to_data_url(c_path)\n",
    "    content = [\n",
    "        {\"type\": \"text\", \"text\": B_USER_PROMPT},\n",
    "        {\"type\": \"text\", \"text\": \"图像1（query）：\"},\n",
    "        {\"type\": \"image_url\", \"image_url\": {\"url\": q}},\n",
    "        {\"type\": \"text\", \"text\": \"图像2（candidate）：\"},\n",
    "        {\"type\": \"image_url\", \"image_url\": {\"url\": c}},\n",
    "    ]\n",
    "    payload = {\n",
    "        \"model\": MODEL_8B,\n",
    "        \"messages\": [\n",
    "            {\"role\": \"system\", \"content\": B_SYSTEM_PROMPT},\n",
    "            {\"role\": \"user\", \"content\": content},\n",
    "        ],\n",
    "        \"temperature\": 0.0,\n",
    "    }\n",
    "    j = request_json(LLM_8B_URL, payload, TIMEOUT_8B, RETRY_8B)\n",
    "    msg = j[\"choices\"][0][\"message\"][\"content\"]\n",
    "    obj = extract_json(msg)\n",
    "    validate_b(obj)\n",
    "    return obj\n",
    "\n",
    "def step_B():\n",
    "    done = read_done_set(B_DONE)\n",
    "    print(f\"[B] resume done={len(done)}\")\n",
    "    pbar = tqdm(desc=\"Step B (8B review)\", total=(MAX_PAIRS if MAX_PAIRS else None), ncols=100)\n",
    "\n",
    "    try:\n",
    "        with B_OUT.open(\"a\", encoding=\"utf-8\") as fw, B_DONE.open(\"a\", encoding=\"utf-8\") as fd:\n",
    "            for it in iter_pairs():\n",
    "                k = key_of(it[\"query_image_id\"], it[\"candidate_image_id\"])\n",
    "                if RESUME and k in done:\n",
    "                    pbar.update(1)\n",
    "                    continue\n",
    "                try:\n",
    "                    obj = call_8b_pair_review(it[\"query_path\"], it[\"candidate_path\"])\n",
    "                    out = {\n",
    "                        \"schema\": \"b_pair_review_v3\",\n",
    "                        \"query_image_id\": it[\"query_image_id\"],\n",
    "                        \"candidate_image_id\": it[\"candidate_image_id\"],\n",
    "                        \"query_path\": it[\"query_path\"],\n",
    "                        \"candidate_path\": it[\"candidate_path\"],\n",
    "                        \"b\": obj,\n",
    "                    }\n",
    "                    fw.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "                    fd.write(k + \"\\n\")\n",
    "                    done.add(k)\n",
    "                except Exception as <LOCAL_DRIVE_E>\n",
    "                    append_fail(B_FAIL, {\n",
    "                        \"when\": now_iso(), \"stage\": \"B\", \"key\": k,\n",
    "                        \"query_path\": it[\"query_path\"], \"candidate_path\": it[\"candidate_path\"],\n",
    "                        \"error\": str(e)\n",
    "                    })\n",
    "                    if FAIL_FAST_GLOBAL:\n",
    "                        raise\n",
    "                pbar.update(1)\n",
    "    finally:\n",
    "        pbar.close()\n",
    "    print(f\"[B] done -> {B_OUT}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 7) Step C: polygon_v4 + mask-clip delta (offline CLIP)\n",
    "# =========================\n",
    "def call_8b_polygon(q_path: str, c_path: str) -> dict:\n",
    "    q = img_to_data_url(q_path)\n",
    "    c = img_to_data_url(c_path)\n",
    "    content = [\n",
    "        {\"type\": \"text\", \"text\": C_USER_PROMPT},\n",
    "        {\"type\": \"text\", \"text\": \"图像1（query）：\"},\n",
    "        {\"type\": \"image_url\", \"image_url\": {\"url\": q}},\n",
    "        {\"type\": \"text\", \"text\": \"图像2（candidate）：\"},\n",
    "        {\"type\": \"image_url\", \"image_url\": {\"url\": c}},\n",
    "    ]\n",
    "    payload = {\n",
    "        \"model\": MODEL_8B,\n",
    "        \"messages\": [\n",
    "            {\"role\": \"system\", \"content\": C_SYSTEM_PROMPT},\n",
    "            {\"role\": \"user\", \"content\": content},\n",
    "        ],\n",
    "        \"temperature\": TEMP_8B_POLY,\n",
    "    }\n",
    "    j = request_json(LLM_8B_URL, payload, TIMEOUT_8B, RETRY_8B)\n",
    "    msg = j[\"choices\"][0][\"message\"][\"content\"]\n",
    "    obj = extract_json(msg)\n",
    "    validate_poly(obj)\n",
    "\n",
    "    # enforce tau rule: YES but conf < TAU_NOISE -> treat as NO\n",
    "    if obj[\"noise_decision\"] == \"YES\" and float(obj[\"noise_confidence\"]) < TAU_NOISE:\n",
    "        obj[\"noise_decision\"] = \"NO\"\n",
    "        obj[\"noise_type\"] = \"none\"\n",
    "        obj[\"polygons\"] = []\n",
    "        obj[\"reason_zh\"] = obj[\"reason_zh\"] + \"（低置信->按规则视为NO）\"\n",
    "    return obj\n",
    "\n",
    "def step_C():\n",
    "    done = read_done_set(C_DONE)\n",
    "    print(f\"[C] resume done={len(done)}\")\n",
    "\n",
    "    DEVICE = \"cuda\" if torch.cuda.is_available() else \"cpu\"\n",
    "    DTYPE = torch.float16 if DEVICE == \"cuda\" else torch.float32\n",
    "    print(f\"[C] device={DEVICE} dtype={DTYPE}\")\n",
    "\n",
    "    processor = CLIPProcessor.from_pretrained(str(LOCAL_CLIP_DIR), local_files_only=True)\n",
    "    model = CLIPModel.from_pretrained(\n",
    "        str(LOCAL_CLIP_DIR),\n",
    "        local_files_only=True,\n",
    "        torch_dtype=DTYPE if DEVICE == \"cuda\" else None,\n",
    "    ).to(DEVICE).eval()\n",
    "\n",
    "    def clip_sim(img1: Image.Image, img2: Image.Image) -> float:\n",
    "        inputs = processor(images=[img1, img2], return_tensors=\"pt\")\n",
    "        inputs = {k: v.to(DEVICE) for k, v in inputs.items()}\n",
    "        with torch.no_grad():\n",
    "            feats = model.get_image_features(**inputs)\n",
    "            feats = feats / feats.norm(dim=-1, keepdim=True)\n",
    "            sim = float((feats[0] * feats[1]).sum().item())\n",
    "        return sim\n",
    "\n",
    "    pbar = tqdm(desc=\"Step C (polygon+delta)\", total=(MAX_PAIRS if MAX_PAIRS else None), ncols=100)\n",
    "\n",
    "    try:\n",
    "        with C_OUT.open(\"a\", encoding=\"utf-8\") as fw, C_DONE.open(\"a\", encoding=\"utf-8\") as fd:\n",
    "            for it in iter_pairs():\n",
    "                k = key_of(it[\"query_image_id\"], it[\"candidate_image_id\"])\n",
    "                if RESUME and k in done:\n",
    "                    pbar.update(1)\n",
    "                    continue\n",
    "                try:\n",
    "                    poly = call_8b_polygon(it[\"query_path\"], it[\"candidate_path\"])  # may raise\n",
    "\n",
    "                    q_img = Image.open(it[\"query_path\"]).convert(\"RGB\")\n",
    "                    c_img = Image.open(it[\"candidate_path\"]).convert(\"RGB\")\n",
    "\n",
    "                    sim_raw = clip_sim(q_img, c_img)\n",
    "                    sim_masked = sim_raw\n",
    "                    delta = 0.0\n",
    "                    cover_raw = 0.0\n",
    "                    cover_cap = 0.0\n",
    "\n",
    "                    if poly[\"noise_decision\"] == \"YES\":\n",
    "                        q_m, cover_q = mask_image_with_polys(q_img, poly[\"polygons\"])\n",
    "                        c_m, cover_c = mask_image_with_polys(c_img, poly[\"polygons\"])\n",
    "                        cover_raw = max(cover_q, cover_c)\n",
    "                        cover_cap = min(cover_raw, COVER_CAP)\n",
    "                        sim_masked = clip_sim(q_m, c_m)\n",
    "                        delta = float(sim_masked - sim_raw)\n",
    "\n",
    "                    if poly[\"noise_decision\"] == \"YES\" and delta <= DELTA_STRONG:\n",
    "                        c_decision = \"REJECT\"\n",
    "                        c_explain = f\"噪声遮蔽后相似度显著下降(delta={delta:.3f})，怀疑原相似度被噪声抬高\"\n",
    "                    else:\n",
    "                        c_decision = \"AMBIGUOUS\"\n",
    "                        c_explain = \"未观察到噪声导致的强反证（或噪声不存在）\"\n",
    "\n",
    "                    out = {\n",
    "                        \"schema\": \"c_noise_maskclip_v4\",\n",
    "                        \"query_image_id\": it[\"query_image_id\"],\n",
    "                        \"candidate_image_id\": it[\"candidate_image_id\"],\n",
    "                        \"query_path\": it[\"query_path\"],\n",
    "                        \"candidate_path\": it[\"candidate_path\"],\n",
    "                        \"polygon\": poly,\n",
    "                        \"cover_frac_raw\": safe_float(cover_raw),\n",
    "                        \"cover_frac_capped\": safe_float(cover_cap),\n",
    "                        \"mask_clip_raw\": safe_float(sim_raw),\n",
    "                        \"mask_clip_masked\": safe_float(sim_masked),\n",
    "                        \"mask_clip_delta\": safe_float(delta),\n",
    "                        \"C_decision\": c_decision,\n",
    "                        \"C_explain\": c_explain,\n",
    "                    }\n",
    "\n",
    "                    fw.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "                    fd.write(k + \"\\n\")\n",
    "                    done.add(k)\n",
    "\n",
    "                except Exception as <LOCAL_DRIVE_E>\n",
    "                    append_fail(C_FAIL, {\n",
    "                        \"when\": now_iso(), \"stage\": \"C\", \"key\": k,\n",
    "                        \"query_path\": it[\"query_path\"], \"candidate_path\": it[\"candidate_path\"],\n",
    "                        \"error\": str(e)\n",
    "                    })\n",
    "                    if FAIL_FAST_GLOBAL:\n",
    "                        raise\n",
    "\n",
    "                pbar.update(1)\n",
    "    finally:\n",
    "        pbar.close()\n",
    "    print(f\"[C] done -> {C_OUT}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 8) Step Merge: join A/B/C -> auto/dispute\n",
    "# =========================\n",
    "def load_map(path: Path) -> Dict[Tuple[int,int], dict]:\n",
    "    m = {}\n",
    "    with path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            j = json.loads(line)\n",
    "            qid = safe_int(j[\"query_image_id\"])\n",
    "            cid = safe_int(j[\"candidate_image_id\"])\n",
    "            m[(qid, cid)] = j\n",
    "    return m\n",
    "\n",
    "def step_merge_and_dispute():\n",
    "    A = load_map(A_OUT)\n",
    "    B = load_map(B_OUT)\n",
    "    C = load_map(C_OUT)\n",
    "    keys = sorted(set(A.keys()) & set(B.keys()) & set(C.keys()))\n",
    "    print(f\"[MERGE] join keys={len(keys)} (intersection of A/B/C)\")\n",
    "\n",
    "    # resume for merged?\n",
    "    done = read_done_set(Path(str(OUT_DIR / \"m_done_pairs.txt\")))\n",
    "    m_done_path = OUT_DIR / \"m_done_pairs.txt\"\n",
    "\n",
    "    pbar = tqdm(desc=\"Merge -> dispute\", total=len(keys), ncols=100)\n",
    "\n",
    "    with MERGED.open(\"a\", encoding=\"utf-8\") as fm, DISPUTE.open(\"a\", encoding=\"utf-8\") as fd, m_done_path.open(\"a\", encoding=\"utf-8\") as fdone:\n",
    "        for (qid, cid) in keys:\n",
    "            k = key_of(qid, cid)\n",
    "            if RESUME and k in done:\n",
    "                pbar.update(1); continue\n",
    "\n",
    "            a = A[(qid, cid)]\n",
    "            b = B[(qid, cid)]\n",
    "            c = C[(qid, cid)]\n",
    "\n",
    "            A_vote = vote_from_A(a[\"A_decision\"])\n",
    "            B_vote = vote_from_B(b[\"b\"][\"final_recommendation\"])\n",
    "            C_vote = vote_from_C(c)\n",
    "\n",
    "            auto_final = two_of_three(A_vote, B_vote, C_vote)\n",
    "\n",
    "            force_dispute = False\n",
    "            if FORCE_DISPUTE_ON_C_STRONG:\n",
    "                if c[\"polygon\"][\"noise_decision\"] == \"YES\" and float(c[\"mask_clip_delta\"]) <= DELTA_STRONG:\n",
    "                    force_dispute = True\n",
    "\n",
    "            merged = {\n",
    "                \"schema\": \"merged_abc_votes_v1\",\n",
    "                \"query_image_id\": qid,\n",
    "                \"candidate_image_id\": cid,\n",
    "                \"query_path\": a[\"query_path\"],\n",
    "                \"candidate_path\": a[\"candidate_path\"],\n",
    "                \"A\": {\"decision\": a[\"A_decision\"], \"score\": a[\"clip_similarity\"], \"rank\": a[\"A_rank\"], \"vote\": A_vote},\n",
    "                \"B\": {\"final\": b[\"b\"][\"final_recommendation\"], \"conf\": b[\"b\"][\"confidence\"], \"criteria\": b[\"b\"][\"criteria\"], \"vote\": B_vote},\n",
    "                \"C\": {\"noise\": c[\"polygon\"][\"noise_decision\"], \"noise_conf\": c[\"polygon\"][\"noise_confidence\"],\n",
    "                      \"cover_raw\": c[\"cover_frac_raw\"], \"cover_cap\": c[\"cover_frac_capped\"],\n",
    "                      \"raw\": c[\"mask_clip_raw\"], \"masked\": c[\"mask_clip_masked\"], \"delta\": c[\"mask_clip_delta\"],\n",
    "                      \"decision\": c[\"C_decision\"], \"explain\": c[\"C_explain\"], \"vote\": C_vote},\n",
    "                \"auto_final\": (auto_final if (auto_final and not force_dispute) else None),\n",
    "                \"force_dispute\": force_dispute,\n",
    "            }\n",
    "\n",
    "            fm.write(json.dumps(merged, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "            if merged[\"auto_final\"] is None or merged[\"force_dispute\"]:\n",
    "                fd.write(json.dumps(merged, ensure_ascii=False) + \"\\n\")\n",
    "\n",
    "            fdone.write(k + \"\\n\")\n",
    "            done.add(k)\n",
    "            pbar.update(1)\n",
    "\n",
    "    pbar.close()\n",
    "    print(f\"[MERGE] done -> {MERGED}\")\n",
    "    print(f\"[MERGE] dispute -> {DISPUTE}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 9) Step D: Teacher on disputes (evidence-only)\n",
    "# =========================\n",
    "def call_teacher(user_prompt: str) -> dict:\n",
    "    payload = {\n",
    "        \"model\": MODEL_30B,\n",
    "        \"messages\": [\n",
    "            {\"role\": \"system\", \"content\": D_SYSTEM_PROMPT},\n",
    "            {\"role\": \"user\", \"content\": user_prompt},\n",
    "        ],\n",
    "        \"temperature\": 0.0,\n",
    "    }\n",
    "    j = request_json(LLM_30B_URL, payload, TIMEOUT_30B, RETRY_30B)\n",
    "    msg = j[\"choices\"][0][\"message\"][\"content\"]\n",
    "    obj = extract_json(msg)\n",
    "    if obj.get(\"schema\") != \"prf_teacher_arbitration_v1\":\n",
    "        raise ValueError(f\"bad teacher schema: {obj.get('schema')}\")\n",
    "    if obj[\"final_decision\"] not in [\"ACCEPT\",\"REJECT\",\"AMBIGUOUS\"]:\n",
    "        raise ValueError(\"bad teacher final_decision\")\n",
    "    # adopted/overruled sanity (light)\n",
    "    if set(obj.get(\"adopted_from\", [])) & set(obj.get(\"overruled\", [])):\n",
    "        raise ValueError(\"teacher adopted_from intersects overruled\")\n",
    "    return obj\n",
    "\n",
    "def step_teacher():\n",
    "    done = read_done_set(T_DONE)\n",
    "    print(f\"[T] resume done={len(done)}\")\n",
    "    total = 0\n",
    "    # count disputes first for progress bar\n",
    "    with DISPUTE.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if line.strip():\n",
    "                total += 1\n",
    "\n",
    "    pbar = tqdm(desc=\"Teacher 30B (disputes)\", total=total, ncols=100)\n",
    "\n",
    "    with DISPUTE.open(\"r\", encoding=\"utf-8\") as fr, T_OUT.open(\"a\", encoding=\"utf-8\") as fw, T_DONE.open(\"a\", encoding=\"utf-8\") as fd:\n",
    "        for line in fr:\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            j = json.loads(line)\n",
    "            qid = safe_int(j[\"query_image_id\"]); cid = safe_int(j[\"candidate_image_id\"])\n",
    "            k = key_of(qid, cid)\n",
    "            if RESUME and k in done:\n",
    "                pbar.update(1); continue\n",
    "            try:\n",
    "                a = j[\"A\"]; b = j[\"B\"]; c = j[\"C\"]\n",
    "                user = D_USER_TEMPLATE.format(\n",
    "                    A_decision=a[\"decision\"], A_score=f'{float(a[\"score\"]):.4f}', A_rank=a[\"rank\"],\n",
    "                    B_pixel=b[\"criteria\"][\"pixel_consistency\"][\"score\"],\n",
    "                    B_base=b[\"criteria\"][\"same_base_image\"][\"score\"],\n",
    "                    B_instance=b[\"criteria\"][\"same_instance\"][\"score\"],\n",
    "                    B_strong=b[\"criteria\"][\"strong_structure\"][\"score\"],\n",
    "                    B_weak=b[\"criteria\"][\"weak_structure\"][\"score\"],\n",
    "                    B_decision=b[\"final\"], B_conf=f'{float(b[\"conf\"]):.3f}',\n",
    "                    C_noise=c[\"noise\"], C_cover_raw=f'{float(c[\"cover_raw\"]):.4f}', C_cover_cap=f'{float(c[\"cover_cap\"]):.4f}',\n",
    "                    C_clip_raw=f'{float(c[\"raw\"]):.4f}', C_clip_masked=f'{float(c[\"masked\"]):.4f}', C_delta=f'{float(c[\"delta\"]):.4f}',\n",
    "                    C_decision=c[\"decision\"], C_explain=c[\"explain\"],\n",
    "                )\n",
    "\n",
    "                t = call_teacher(user)\n",
    "                out = {\n",
    "                    \"schema\": \"teacher_30b_full_v1\",\n",
    "                    \"query_image_id\": qid,\n",
    "                    \"candidate_image_id\": cid,\n",
    "                    \"teacher\": t,\n",
    "                }\n",
    "                fw.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "                fd.write(k + \"\\n\")\n",
    "                done.add(k)\n",
    "\n",
    "            except Exception as <LOCAL_DRIVE_E>\n",
    "                append_fail(T_FAIL, {\"when\": now_iso(), \"stage\": \"T\", \"key\": k, \"error\": str(e)})\n",
    "                if FAIL_FAST_GLOBAL:\n",
    "                    raise\n",
    "\n",
    "            pbar.update(1)\n",
    "\n",
    "    pbar.close()\n",
    "    print(f\"[T] done -> {T_OUT}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 10) Build Mother U (auto + teacher)\n",
    "# =========================\n",
    "def step_build_U():\n",
    "    done = read_done_set(U_DONE)\n",
    "    print(f\"[U] resume done={len(done)}\")\n",
    "\n",
    "    # teacher map\n",
    "    Tm = {}\n",
    "    if T_OUT.exists():\n",
    "        with T_OUT.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "            for line in <LOCAL_DRIVE_F>\n",
    "                if not line.strip():\n",
    "                    continue\n",
    "                j = json.loads(line)\n",
    "                qid = safe_int(j[\"query_image_id\"])\n",
    "                cid = safe_int(j[\"candidate_image_id\"])\n",
    "                Tm[(qid,cid)] = j[\"teacher\"]\n",
    "\n",
    "    # count merged for progress\n",
    "    total = 0\n",
    "    with MERGED.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if line.strip():\n",
    "                total += 1\n",
    "\n",
    "    pbar = tqdm(desc=\"Build mother U\", total=total, ncols=100)\n",
    "\n",
    "    with MERGED.open(\"r\", encoding=\"utf-8\") as fr, U_OUT.open(\"a\", encoding=\"utf-8\") as fu, U_DONE.open(\"a\", encoding=\"utf-8\") as fd:\n",
    "        for line in fr:\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            j = json.loads(line)\n",
    "            qid = safe_int(j[\"query_image_id\"]); cid = safe_int(j[\"candidate_image_id\"])\n",
    "            k = key_of(qid, cid)\n",
    "            if RESUME and k in done:\n",
    "                pbar.update(1); continue\n",
    "\n",
    "            try:\n",
    "                if j[\"auto_final\"] is not None and not j[\"force_dispute\"]:\n",
    "                    final = j[\"auto_final\"]\n",
    "                    src = \"AUTO_2OF3\"\n",
    "                    teacher = None\n",
    "                else:\n",
    "                    teacher = Tm.get((qid,cid))\n",
    "                    if teacher is None:\n",
    "                        raise ValueError(\"missing teacher output for dispute pair\")\n",
    "                    final = teacher[\"final_decision\"]\n",
    "                    src = \"TEACHER_30B\"\n",
    "\n",
    "                out = {\n",
    "                    \"schema\": \"mother_U_v1\",\n",
    "                    \"query_image_id\": qid,\n",
    "                    \"candidate_image_id\": cid,\n",
    "                    \"query_path\": j[\"query_path\"],\n",
    "                    \"candidate_path\": j[\"candidate_path\"],\n",
    "                    \"final_decision\": final,\n",
    "                    \"final_source\": src,\n",
    "                    \"force_dispute\": bool(j[\"force_dispute\"]),\n",
    "                    \"A\": j[\"A\"],\n",
    "                    \"B\": {\"final\": j[\"B\"][\"final\"], \"conf\": j[\"B\"][\"conf\"]},\n",
    "                    \"C\": {\"noise\": j[\"C\"][\"noise\"], \"delta\": j[\"C\"][\"delta\"], \"decision\": j[\"C\"][\"decision\"]},\n",
    "                    \"teacher\": teacher,\n",
    "                }\n",
    "                fu.write(json.dumps(out, ensure_ascii=False) + \"\\n\")\n",
    "                fd.write(k + \"\\n\")\n",
    "                done.add(k)\n",
    "\n",
    "            except Exception as <LOCAL_DRIVE_E>\n",
    "                append_fail(U_FAIL, {\"when\": now_iso(), \"stage\": \"U\", \"key\": k, \"error\": str(e)})\n",
    "                if FAIL_FAST_GLOBAL:\n",
    "                    raise\n",
    "\n",
    "            pbar.update(1)\n",
    "\n",
    "    pbar.close()\n",
    "    print(f\"[U] done -> {U_OUT}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 11) run_summary.json\n",
    "# =========================\n",
    "def summarize_jsonl(path: Path, key_fields=(\"final_decision\",), limit=None):\n",
    "    cnt = {}\n",
    "    n = 0\n",
    "    if not path.exists():\n",
    "        return {\"n\": 0}\n",
    "    with path.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            j = json.loads(line)\n",
    "            n += 1\n",
    "            for k in key_fields:\n",
    "                v = j.get(k)\n",
    "                if v is None:\n",
    "                    continue\n",
    "                cnt[str(v)] = cnt.get(str(v), 0) + 1\n",
    "            if limit and n >= limit:\n",
    "                break\n",
    "    return {\"n\": n, \"dist\": cnt}\n",
    "\n",
    "def compute_run_summary():\n",
    "    # count disputes etc.\n",
    "    merged_n = 0\n",
    "    auto_n = 0\n",
    "    forced_n = 0\n",
    "    with MERGED.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        for line in <LOCAL_DRIVE_F>\n",
    "            if not line.strip():\n",
    "                continue\n",
    "            j = json.loads(line)\n",
    "            merged_n += 1\n",
    "            if j.get(\"force_dispute\"):\n",
    "                forced_n += 1\n",
    "            if j.get(\"auto_final\") is not None and not j.get(\"force_dispute\"):\n",
    "                auto_n += 1\n",
    "\n",
    "    dispute_n = 0\n",
    "    if DISPUTE.exists():\n",
    "        with DISPUTE.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "            for line in <LOCAL_DRIVE_F>\n",
    "                if line.strip():\n",
    "                    dispute_n += 1\n",
    "\n",
    "    teacher_stats = summarize_jsonl(T_OUT, key_fields=(\"schema\",), limit=None)\n",
    "    u_stats = summarize_jsonl(U_OUT, key_fields=(\"final_decision\",\"final_source\"), limit=None)\n",
    "\n",
    "    # C noise stats quick scan\n",
    "    noise_yes = 0; noise_no = 0\n",
    "    delta_tail = {\"<=-0.1\":0,\"<=-0.2\":0,\"<=-0.3\":0}\n",
    "    cover_vals = []\n",
    "    if C_OUT.exists():\n",
    "        with C_OUT.open(\"r\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "            for line in <LOCAL_DRIVE_F>\n",
    "                if not line.strip(): continue\n",
    "                j = json.loads(line)\n",
    "                nd = j[\"polygon\"][\"noise_decision\"]\n",
    "                if nd == \"YES\": noise_yes += 1\n",
    "                else: noise_no += 1\n",
    "                d = float(j[\"mask_clip_delta\"])\n",
    "                if d <= -0.1: delta_tail[\"<=-0.1\"] += 1\n",
    "                if d <= -0.2: delta_tail[\"<=-0.2\"] += 1\n",
    "                if d <= -0.3: delta_tail[\"<=-0.3\"] += 1\n",
    "                cover_vals.append(float(j[\"cover_frac_capped\"]))\n",
    "\n",
    "    cover_p90 = None\n",
    "    if cover_vals:\n",
    "        cover_p90 = float(np.quantile(np.array(cover_vals, dtype=np.float32), 0.90))\n",
    "\n",
    "    summary = {\n",
    "        \"run_name\": f\"PRF_full_{N_IMG}_imgs_{('all' if MAX_PAIRS is None else MAX_PAIRS)}pairs\",\n",
    "        \"timestamp\": now_iso(),\n",
    "        \"root\": str(ROOT),\n",
    "        \"out_dir\": str(OUT_DIR),\n",
    "        \"inputs\": {\n",
    "            \"pairs_in\": str(PAIRS_IN),\n",
    "            \"manifest\": str(MANIFEST),\n",
    "            \"clip_cache_mmp\": str(CLIP_MMP),\n",
    "            \"clip_local_dir\": str(LOCAL_CLIP_DIR),\n",
    "        },\n",
    "        \"endpoints\": {\n",
    "            \"8b\": LLM_8B_URL,\n",
    "            \"30b\": LLM_30B_URL,\n",
    "        },\n",
    "        \"frozen_params\": {\n",
    "            \"B_prompt_schema\": \"pair_review_v3\",\n",
    "            \"C_prompt_schema\": \"polygon_v4\",\n",
    "            \"TAU_NOISE\": TAU_NOISE,\n",
    "            \"MAX_POLY\": MAX_POLY,\n",
    "            \"COVER_CAP\": COVER_CAP,\n",
    "            \"DELTA_STRONG\": DELTA_STRONG,\n",
    "            \"vote_rule\": \"2-of-3 + C strong gate -> Teacher\",\n",
    "            \"teacher_schema\": \"prf_teacher_arbitration_v1\",\n",
    "        },\n",
    "        \"counts\": {\n",
    "            \"merged_pairs\": merged_n,\n",
    "            \"auto_resolved\": auto_n,\n",
    "            \"forced_dispute_by_C_strong\": forced_n,\n",
    "            \"dispute_pairs\": dispute_n,\n",
    "        },\n",
    "        \"noise_stats\": {\n",
    "            \"noise_yes\": noise_yes,\n",
    "            \"noise_no\": noise_no,\n",
    "            \"noise_yes_ratio\": (noise_yes / max(1, noise_yes + noise_no)),\n",
    "            \"cover_frac_capped_p90\": cover_p90,\n",
    "            \"delta_tail_counts\": delta_tail,\n",
    "        },\n",
    "        \"mother_U\": u_stats,\n",
    "        \"files\": {\n",
    "            \"A\": str(A_OUT),\n",
    "            \"B\": str(B_OUT),\n",
    "            \"C\": str(C_OUT),\n",
    "            \"MERGED\": str(MERGED),\n",
    "            \"DISPUTE\": str(DISPUTE),\n",
    "            \"TEACHER\": str(T_OUT),\n",
    "            \"U\": str(U_OUT),\n",
    "        },\n",
    "        \"fail_files\": {\n",
    "            \"A_FAIL\": str(A_FAIL),\n",
    "            \"B_FAIL\": str(B_FAIL),\n",
    "            \"C_FAIL\": str(C_FAIL),\n",
    "            \"T_FAIL\": str(T_FAIL),\n",
    "            \"U_FAIL\": str(U_FAIL),\n",
    "        }\n",
    "    }\n",
    "\n",
    "    with SUMMARY.open(\"w\", encoding=\"utf-8\") as <LOCAL_DRIVE_F>\n",
    "        json.dump(summary, f, ensure_ascii=False, indent=2)\n",
    "    print(f\"[SUMMARY] wrote -> {SUMMARY}\")\n",
    "\n",
    "\n",
    "# =========================\n",
    "# 12) Main\n",
    "# =========================\n",
    "def main():\n",
    "    # sanity\n",
    "    for p in [PAIRS_IN, MANIFEST, CLIP_MMP]:\n",
    "        assert p.exists(), f\"Missing required input: {p}\"\n",
    "\n",
    "    print(\"[RUN] Stage A...\")\n",
    "    step_A()\n",
    "\n",
    "    print(\"[RUN] Stage B...\")\n",
    "    step_B()\n",
    "\n",
    "    print(\"[RUN] Stage C...\")\n",
    "    step_C()\n",
    "\n",
    "    print(\"[RUN] Merge + Dispute...\")\n",
    "    step_merge_and_dispute()\n",
    "\n",
    "    print(\"[RUN] Teacher on Disputes...\")\n",
    "    step_teacher()\n",
    "\n",
    "    print(\"[RUN] Build Mother U...\")\n",
    "    step_build_U()\n",
    "\n",
    "    print(\"[RUN] run_summary.json ...\")\n",
    "    compute_run_summary()\n",
    "\n",
    "    print(\"[DONE] Pipeline complete.\")\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    main()\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "e824a370-8d7e-4421-9fde-d7c265fb7010",
   "metadata": {},
   "outputs": [],
   "source": []
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "ec2eb196-8331-4213-bd51-8cf21ee3280a",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "rtx5090_final (CUDA13.1)",
   "language": "python",
   "name": "rtx5090_final"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.10.19"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
